# Generated by Django 4.0.3 on 2022-04-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tex',
            new_name='text',
        ),
    ]
